def delivery_address():
    print("\n =======================================================================")
    print("\n\t Enter your Delivery Address Details : ")
    flat_no = int(input("\t Flat Number : "))
    bldg_name = input("\t Building Name : ")
    strt_name = input("\t Street : ")
    area = input("\t Area : ")
    city = input("\t City : ")
    state = input("\t State : ")
    landmark = input("\t Landmark : ")
    print("\n =======================================================================")

def payment():
    print("\n =======================================================================")
    print("\n\t 1. Cash On Delivery \n\t 2. Online Payment ")
    a = int(input("\n\t Choose n Payment Option : "))
    if a == 1 :
        clear()
        delivery_address()
        clear()
        receipt()
        print("\n Your Order Has Been Placed. It will get delivered by a week! ")
        print(" \n\n    T H A N K    Y O U    F O R   S H O P P I N G   W I T H    U S   !")
    if a == 2 :
        clear()
        print("\n 1. Credit Card \n 2. Debit Card. ")
        c = int(input("\n\n Choose your Card : "))
        customer_credit_debit()
        clear()
        delivery_address()
        clear()
        receipt()
        print("\n Your Order Has Been Placed. It will get delivered by a week! ")
        print(" \n\n    T H A N K    Y O U    F O R   S H O P P I N G   W I T H    U S   !")
    print("\n =======================================================================")
    cursor.execute('''DELETE FROM BASKET;''')
    mydb.commit()
